language: php

dist: xenial

php:
  - 7.3

env:
  global:
    - SITE_URL="http://links-dev"
    - SITE_DOMAIN="links-dev"
    - DB_NAME="testing"

sudo:
  required

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update -q

install:
  - travis_retry composer install --no-interaction

before_script:
  - sudo sed -i "2i127.0.1.1 links-dev links-dev.test m.links-dev s.links-dev m.links-dev.test s.links-dev.test" /etc/hosts
  - sudo apt-get install -q php7.3-mysql
  - sudo apt-get install -q php7.3-xml
  - sudo apt-get install -q php7.3-json
  - sudo apt-get install -q php7.3-curl
  - sudo apt-get install -q php7.3-gd
  - sudo apt-get install -q php7.3-fpm
  - sudo apt-get install -q php7.3-cli
  - sudo apt-get install -q php7.3-mbstring
  - sudo apt-get install -q php7.3-zip
  - sudo apt-get install -q libnss3-dev libxi6 libgconf-2-4
  - cp .env.travis .env
  - cp phpunit.travis.xml phpunit.xml
  - mysql -e 'create database testing;'
  - sudo cp travis-nginx-conf /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo sed -i 's/^;opcache.interned_strings_buffer=8.*/opcache.interned_strings_buffer=8/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.max_accelerated_files=10000.*/opcache.max_accelerated_files=5000/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.revalidate_freq=2.*/opcache.revalidate_freq=60/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.fast_shutdown=0.*/opcache.fast_shutdown=1/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.validate_timestamps=1.*/opcache.validate_timestamps=0/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.enable=0.*/opcache.enable=1/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.enable_cli=0.*/opcache.enable_cli=1/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.memory_consumption=128.*/opcache.memory_consumption=1024/' /etc/php/7.3/fpm/php.ini
  - sudo sed -i 's/^;opcache.enable=0.*/opcache.enable=1/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.enable_cli=0.*/opcache.enable_cli=1/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.max_accelerated_files=10000.*/opcache.max_accelerated_files=5000/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.revalidate_freq=2.*/opcache.revalidate_freq=60/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.memory_consumption=128.*/opcache.memory_consumption=1024/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.interned_strings_buffer=8.*/opcache.interned_strings_buffer=8/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.fast_shutdown=0.*/opcache.fast_shutdown=1/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^;opcache.validate_timestamps=1.*/opcache.validate_timestamps=0/' /etc/php/7.3/cli/php.ini
  - sudo sed -i 's/^worker_processes 4;.*/worker_processes 6;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/worker_connections 768;.*/worker_connections 8096;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/# multi_accept on;.*/multi_accept on; use epoll;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nproxy_read_timeout 600;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nsend_timeout 600;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nclient_body_buffer_size 10K;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nproxy_connect_timeout 600;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nproxy_send_timeout 600;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nclient_header_buffer_size 1k;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nclient_max_body_size 8m;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/http {/http \{\nlarge_client_header_buffers 2 1k;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/pm.max_children = 5/pm.max_children = 50/' /etc/php/7.3/fpm/pool.d/www.conf
  - sudo sed -i 's/pm.start_servers = 2/pm.start_servers = 5/' /etc/php/7.3/fpm/pool.d/www.conf
  - sudo sed -i 's/pm.min_spare_servers = 1/pm.min_spare_servers = 5/' /etc/php/7.3/fpm/pool.d/www.conf
  - sudo sed -i 's/pm.max_spare_servers = 3/pm.max_spare_servers = 35/' /etc/php/7.3/fpm/pool.d/www.conf
  - sudo sed -i 's/;request_terminate_timeout = 0/request_terminate_timeout = 30s/' /etc/php/7.3/fpm/pool.d/www.conf
  - sudo sed -e "s?%SITE_DOMAIN%?$SITE_DOMAIN?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo ln -s /etc/nginx/sites-available/$SITE_DOMAIN /etc/nginx/sites-enabled/
  - sudo sed -i 's/^user www-data;.*/user travis;/' /etc/nginx/nginx.conf
  - sudo sed -i 's/www-data/travis/g' /etc/php/7.3/fpm/pool.d/www.conf
  - sudo service php7.3-fpm restart
  - sudo service nginx restart
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit

services:
  - redis-server
  - mysql

addons:
  apt:
    packages:
      - nginx

hosts: "links-dev"

after_success:

