language: minimal

dist: xenial

sudo:
  required

before_install:
  - export UIDX=${UID}

install:
  - docker-compose -f docker-compose.prod.yml up -d

before_script:
  - until ! docker ps| grep composer >>/dev/null; do printf '.'; sleep 1; done
  - docker-compose -f docker-compose.prod.yml exec php php artisan key:generate
  - docker-compose -f docker-compose.prod.yml exec php php artisan migrate --force

script:
  - docker-compose -f docker-compose.prod.yml exec php vendor/bin/phpunit

services:
  - docker

