version: '3'
services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - .:/links
  php:
    build: docker/php
    user: ${UID}:${UIDX}
    working_dir: /links
    restart: always
    volumes:
      - .:/links
  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: links
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
